### ISSUE TITLE
drag (or shift) select in pickerInput

### ISSUE THREAD

**Issue by jonnyrobbie** [dreamRs/shinyWidgets#199]
Is it possible to have a drag-select multiple options in picker input? So I don't have to click every single option. I know there is "Select All" button, but I don't want to select all, only a continuous subset of options. Or maybe shift-select-like feature to emulate selecting files in file explorers.
Thanks

**Comment by trafficonese** [comment]
I would also be very interested in this option.

**Comment by trafficonese** [comment]
I have a local fix, but I had to adapt the underlying `bootsrap-select.min.js`. 
I don't know, if I should upload a PR with it to `shinyWidgets` or rather try to open a PR at the bootsrap-select repo?

There is a similar issue already [here](https://github.com/snapappointments/bootstrap-select/issues/2085), which would also get fixed with it.

**Comment by pvictor** [comment]
Yes, this will not be implemented in the JS library used by `pickerInput`, and I don't know of any JS libraries providing this functionality.
