### ISSUE TITLE
pickerInput won't show inside renderMenu

### ISSUE THREAD

**Issue by alexktan** [dreamRs/shinyWidgets#22]
library(shiny)
library(shinydashboard)
library(shinyWidgets)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(
    
    sidebarMenuOutput("menu"),
    
    sliderInput("x", "Outside of menu", 1, 100, 50)),
  dashboardBody()
)

server <- function(input, output) {
  output$menu <- renderMenu({
    sidebarMenu(id = "sidebarmenu",
                menuItem("A", tabName = "a",  icon = icon("group", lib="font-awesome")),
                menuItem("B", tabName = "b", icon = icon("check-circle", lib = "font-awesome")),
                conditionalPanel("input.sidebarmenu === 'b'",
                                 sliderInput("c", "Under sidebarMenu", 1, 100, 50),
                                 
                                 pickerInput(
                                   inputId = "p1",
                                   label = "Select all option",
                                   choices = rownames(mtcars),
                                   multiple = TRUE,
                                   options = list(`actions-box` = TRUE,`selected-text-format` = "count > 3")
                                 )
                )
    )
  })
}

shinyApp(ui, server)

Thanks for the package, I'm trying to render pickerInput, but it doesn't seem to work under tab b.  Any thoughts to solve this?

Cheers

**Comment by pvictor** [comment]
Hi, thanks for using the package! There's a bug in the last CRAN version when rendering `pickerInput` server-side. That's solved in the version on Github, I'll push again to CRAN by the end of the week.

Nonetheless there's some issue with appearance when used in sidebar because of the dark background, some CSS rules are overwrited, the text of choices in the menu appear grey, you can change this manually with this for example : 

```
tags$style("span.text {color: #000 !important;}")
```
