### ISSUE TITLE
The result of inputSweetAlert does not trigger a reaction when it does not change

### ISSUE THREAD

**Issue by stla** [dreamRs/shinyWidgets#222]
Hello

 You might be interested in [this discussion](https://stackoverflow.com/q/57946686/1100107).

**Comment by ismirsehregal** [comment]
@pvictor thanks for coming back to this on SO!
For something with the visual prominence of a modal, it might make sense to always trigger an event. In this case, especially since the modal's input box always starts empty and the user doesn't get any feedback about the previous entry. Accordingly using `{priority: "event"}` seems to be appropriate.

**Comment by pvictor** [comment]
Thanks both.
I've implemented your suggestion @ismirsehregal .

Victor
