### ISSUE TITLE
How to use fontawesome icon in pickerInput?

### ISSUE THREAD

**Issue by sbihorel** [dreamRs/shinyWidgets#267]
Hi

First, thanks for the awesome package.

I am trying to use fontawesome icons in a pickerInput but don't seem to be able to get the right code to work

The following works with a vector of choices and glyphicon icons. It does not when I switch to fontawesome icons (commented line).

Any advise will be welcome

Ultimately, my goal is to assign fontawesome icons to elements of a list of choices (not a vector).

```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  pickerInput(
    inputId = "somevalue",
    label = "A label",
    choices = letters[1:4],
    # list(
    #   first = c('a', 'b'),
    #   second = c('d', 'e')
    # ),
    choicesOpt = list(
      icon = c('glyphicon-arrow-right', 'glyphicon-arrow-right', 'glyphicon-arrow-right', 'glyphicon-arrow-right') 
      #icon = c('fa fa-check', 'fa fa-cog', 'fa fa-check', 'fa fa-cog')
    ),
    #   list(
    #   icon = list(
    #     first = c('fa fa-check', 'fa fa-times'),
    #     second = c('fa fa-check', 'fa fa-times')
    #   )
    # ),
    multiple = TRUE,
    selected = 'a'
  ),
  verbatimTextOutput("value")
)

server <- function(input, output) {
  output$value <- renderPrint(input$somevalue)
}

shinyApp(ui, server, options = list(launch.browser=TRUE))
```

**Comment by pvictor** [comment]
Hello,

The problem is that FontAwesome is an external dependency, so you have tell "shiny" to load it otherwise it's not included. Here's 3 methods to force FontAwesome to be included :

Method 1 : 
Simply use an icon explicitly somewhere in your application : 
```r
fluidPage(  
  icon("check")
  # rest of ui ...    
)
```

Method 2 : 
Use an icon but hide with CSS: 
```r
fluidPage(  
  tags$div(icon("check"), style = "display: none;"),
  # rest of ui ...    
)
```

Method 3 : 
Find dependencies with {htmltools} : 
```r
fluidPage(  
  htmltools::findDependencies(icon("check")),
  # rest of ui ...    
)
```

Now that FontAwesome is included you can use icons as character string in `pickerInput`, you just have to set two options with `pickerOptions()` to switch from glyphicon to FontAwesome : 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  
  # Method 1
  icon("check"),
  
  # Method 2
  # tags$div(icon("check"), style = "display: none;"),
  
  # Method 3
  # htmltools::findDependencies(icon("check")),
  
  
  pickerInput(
    inputId = "somevalue",
    label = "A label",
    # choices = letters[1:4],
    choices = list(
      first = c("a", "b"),
      second = c("d", "e")
    ),
    choicesOpt = list(
      icon = c("fa-check", "fa-cog", "fa-check", "fa-cog")
    ),
    options = pickerOptions(
      iconBase = "fa", # prefix icons with this value
      tickIcon = "fa-check-circle" # icon used when choice is selected
    ),
    multiple = TRUE,
    selected = "a"
  ),
  verbatimTextOutput("value")
)

server <- function(input, output) {
  output$value <- renderPrint(input$somevalue)
}

shinyApp(ui, server, options = list(launch.browser=TRUE))
```

It doesn't matter if the choices are a list or a vector, the icons must be a vector with as many elements as the list/vector.

Victor

**Comment by sbihorel** [comment]
Thanks.

May I suggest an update of the man page for pickerInput to add more details about fontawesome?
