### ISSUE TITLE
help with countSelectedText option

### ISSUE THREAD

**Issue by ChristopherBarrington** [dreamRs/shinyWidgets#290]
From the documentation

> When set to a function, the first parameter is the number of selected options, and the second is the total number of options. The function must return a string. Type: string | function; Default: function.

I was expecting that the following would produce a formatted string:

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
    pickerInput(
        inputId = "month",
        label = "Select a month",
        choices = month.name,
        multiple = TRUE,
        options = pickerOptions(
            actionsBox = TRUE,
            title = "Please select a month",
            header = "This is a title",
            selectedTextFormat='count>3',
            countSelectedText=function(s,t) {sprintf('%s month%s selected', s, ifelse(s==1, '', 's'))}
        )
    )
)

server <- function(input, output, session) {
    
}

shinyApp(ui, server)
```

But an error is produced: `ERROR: cannot coerce type 'closure' to vector of type 'character'`.

I understand that I can use `'{0} months'` but I would like to make the rest of the text in the string conditional on the arguments provided. Is this possible? What have I misunderstood?

Thanks for your help

**Comment by pvictor** [comment]
Hello,

That's in fact a JavaScript function, documentation is borrowed from https://developer.snapappointments.com/bootstrap-select/options/, and in the current implementation you can't pass a JavaScript function from R to JS....

The not perfect solution is to use something as `'{0} month(s)'`, sorry I don't have a better one right now.

Victor

**Comment by ChristopherBarrington** [comment]
ok thanks for the update

**Comment by CharlesBordet** [comment]
I know this issue has been closed 4 years ago, but I had the same issue today and couldn't find an explanation on why we couldn't pass R functions to the argument.

 It totally makes sense that the JS library is expecting a JS function and that the `shinyWidgets::pickerInput()` is expecting a string, so we can't pass a JS function easily.

However, I found a way to work around this limitation by passing a JS function as the default configuration of `pickerInput`. See the section **Default Settings** of the `bootstrap-select` document page that Victor linked above (https://developer.snapappointments.com/bootstrap-select/options/).

For example:

```JS
$.fn.selectpicker.Constructor.DEFAULTS.countSelectedText = function(x,y) {
    if (x < y) {
        return 'Selected: ' + x + ' / ' + y;
    } else {
        return 'All selected';
    }
};
```

This function will be used in the `count-selected-text` of all `pickerInput()` of the Shiny app. However, I can always replace the option for a specific `pickerInput` by filling in the `count-selected-text` option (with a string, of course).

This doesn't cover all use cases since we can only configure 1 JS function (but at least it covered mine).

Here is a reproducible example:

```R
library(shiny)

ui <- fluidPage(
    tags$script(
        HTML("$.fn.selectpicker.Constructor.DEFAULTS.countSelectedText = function(x,y) {
            if (x < y) {
                return 'Selected: ' + x + ' / ' + y;
            } else {
                return 'All selected';
            }
        };")
    ),
    shinyWidgets::pickerInput(
        inputId = "test",
        label = "Test",
        choices = LETTERS,
        multiple = TRUE,
        options = list(
            `actions-box` = TRUE,
            `count-selected-text` = "Selected: {0} / {1}",
            `selected-text-format` = "count"
        )
    ),
    shinyWidgets::pickerInput(
        inputId = "test2",
        label = "Test2",
        choices = LETTERS,
        multiple = TRUE,
        options = list(
            `actions-box` = TRUE,
            `selected-text-format` = "count"
        )
    )
)

server <- function(input, output, session) {
    observe({
        print(input$test)
    })
}

shinyApp(ui, server)
```
