### ISSUE TITLE
bug click in pickerInput when is inside dropdownButton

### ISSUE THREAD

**Issue by GiCollini** [dreamRs/shinyWidgets#3]
Hi,

I found this bug. When pickerInput is inside a dropdownButton, clicking on the selection bar does not open the menu.

Here a minimal working example

```R
library("shiny")
library("shinyWidgets")

server <- function(input, output, session) {}

ui <- fluidPage(
  tags$h1("Picker behaviour", style="color: steelblue;"),
  fluidRow(
    column(
      width = 6,
      pickerInput(inputId = "id1", label = "Click works", choices = c("a", "b", "c", "d"))
    ),
    column(
      width = 6,
      dropdownButton(
        pickerInput(inputId = "id2", label = "Click doesn't work", choices = c("a", "b", "c", "d")),
        circle = TRUE,
        status = "default",
        icon = icon("gear"),
        label = "Click on me", tooltip = FALSE, width = NULL)
    )
  )
)


shinyApp(ui = ui, server = server)
```

**Comment by pvictor** [comment]
Hi, thanks for the example. It's due to the fact that `pickerInput` is itself a dropdown, and in Bootstrap you cannot put a dropdown inside a dropdown...

The issue for `bootstrap-select` (for which `pickerInput` is a wrapper) is referenced here : https://github.com/silviomoreto/bootstrap-select/issues/642

I think the only solution for you is to use `selectizeInput`.

Victor

**Comment by GiCollini** [comment]
Hi,

It seems there is no way out.

It is a pity because I really like the layout of pickerInput. It is definitely not the same as selectizeInput.

Many thanks,

G.
