### ISSUE TITLE
Selecting a range of dates using airDatepicker()

### ISSUE THREAD

**Issue by oduilln** [dreamRs/shinyWidgets#329]
When the range argument of airDatepicker is TRUE, you can select a range of dates, but I noticed that by clicking the dates, nothing would stay selected. I then realised that I needed to click and then drag along to select a range of dates.

This seems counterintuitive to me. Is there any way to change this, or is something that I have to use and should simply communicate to the users of the dashboard in the label of the dashboard?

The way I expect the widget to work is that I click the first date, then I click the second date.

You can use the third widget in **demoAirdatepicker()** as an example to see what I mean.

**Comment by pvictor** [comment]
Hello,

Not sure what you mean by that, there's no need to drag, you click on a date then on a second one. This function is based on http://t1m0n.name/air-datepicker/docs/, if there's a difference between JS examples and R implementation I can do something otherwise you should open an issue there.

Victor
