### ISSUE TITLE
Latest shiny break `pickerInput`

### ISSUE THREAD

**Issue by lz100** [dreamRs/shinyWidgets#346]
pickerInput repeatedly opens in the new version of shiny. no error on R or js console. 

shinyWidgets: 0.5.5
shiny: 1.5.0.9007

```r
library(shiny)

ui <- fluidPage(
    shinyWidgets::pickerInput(
        inputId = "targets_delim",
        label = "File delimiter",
        choices = c(Tab="\t", `,`=",", space=" ",
                    `|`="|", `:`=":", `;`=";"),
        options = list(style = "btn-primary")
    )
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```

**Comment by pvictor** [comment]
Thanjs for reporting this. Seems caused by the new accessibility module. I'll find a solution.

Victor

**Comment by wch** [comment]
In Shiny, we had a similar issue with the selectize input, caused by the selectize accessibility plugin:
https://github.com/rstudio/shiny/issues/3207
https://github.com/rstudio/shiny/pull/3212

My understanding is that the `pickerInput` uses a different JS library (not selectize.js). It is possible that some of the other accessibility code in Shiny is interacting with it and that there's a similar problem and solution.

For debugging purposes, you may find it useful to copy a non-minified version of the accessibility plugin over this file in Shiny: `inst/www/shared/bootstrap/accessibility/js/bootstrap-accessibility.min.js`, then install/load Shiny.

**Comment by pvictor** [comment]
Thanks @wch ,

The issue is caused by this event:

```js
    $(document)
      .on('focusout.dropdown.data-api', '.dropdown-menu', function(e){
        var $this = $(this)
          , that = this;
        // since we're trying to close when appropriate,
        // make sure the dropdown is open
        if (!$this.parent().hasClass('open')) {
          return;
        }
        setTimeout(function() {
          if(!$.contains(that, document.activeElement)){
            $this.parent().find('[data-toggle=dropdown]').dropdown('toggle')
          }
        }, 150)
       })
```
In bslib unminified file : https://github.com/rstudio/bslib/blob/01ebe7e6a5ad30e30c252c41046b6efe00899746/inst/lib/bs-a11y-p/plugins/js/bootstrap-accessibility.js#L203

Not sure what it does, but removing it with : 

```js
$(document).off('focusout.dropdown.data-api');
```

fix the issue.
I'm not sure if I can remove it for this specific widget case tho

**Comment by cpsievert** [comment]
This issue lies in the fact that `pickerInput()`'s markup includes more than one `.dropdown-menu` (I'm not sure if that's intentional, but it seems wrong?), which causes this event to fire multiple times, meaning that `.dropdown('toggle')` will end up hiding, then showing. I think it's gonna make sense to fix this upstream in shiny by changing `.dropdown('toggle')` to `.dropdown('hide')`. That being said, I'm not sure this'll warrant an immediate patch fix, so if you want to address this in shinyWidgets, maybe consider adding something like 

```js
$(el).on('focusout.dropdown.data-api', '.dropdown-menu', function(e) {
    e.stopPropagation();
});
```

In the picker's initialize method?

https://github.com/dreamRs/shinyWidgets/blob/7993f70c90f658a447995e0e8ef21d71b493a54d/inst/assets/bootstrap-select/picker-bindings.js#L73-L75

**Comment by pvictor** [comment]
Thanks @cpsievert ,

Yes there's 2 `.dropdown-menu`, they are create by the plugin (https://developer.snapappointments.com/bootstrap-select/examples/), I didn't found an explanation on why.

I tried your solution but with no luck. I removed the bindings from minified file, and used the binding file directly.

**Comment by cpsievert** [comment]
Ok, in the meantime, folks can install the dev version of Shiny for a fix `remotes::install_github("rstudio/shiny")`

**Comment by pvictor** [comment]
Thank you Carson, it works as before :)
