### ISSUE TITLE
Selectize Group Vertical Alignment does not work when inline = FALSE

### ISSUE THREAD

**Issue by MikeCilliers** [dreamRs/shinyWidgets#481]
When I use your code below, the inline = FALSE is not aligning the selectizeGroupUI vertically.
I am using shiny version 1.7.1 and shinyWidgets version 0.6.4

Thank you
Mike

```{r}
library(shiny)
library(shinyWidgets)

data("mpg", package = "ggplot2")

ui <- fluidPage(
  fluidRow(
    column(
      width = 4, 
      selectizeGroupUI(
        id = "my-filters", 
        label = "Filters:",
        inline = FALSE,  ### <<<<<---------------- Add this to use vertical layout
        params = list(
          manufacturer = list(inputId = "manufacturer", title = "Manufacturer:"),
          model = list(inputId = "model", title = "Model:"),
          trans = list(inputId = "trans", title = "Trans:"),
          class = list(inputId = "class", title = "Class:")
        )
      )
    ),
    column(
      width = 8,
      dataTableOutput(outputId = "table")
    )
  )
)

server <- function(input, output, session) {
  res_mod <- callModule(
    module = selectizeGroupServer,
    id = "my-filters",
    data = mpg,
    vars = c("manufacturer", "model", "trans", "class")
  )
  output$table <- renderDataTable(res_mod())
}

shinyApp(ui, server)

```

**Comment by MikeCilliers** [comment]
See https://github.com/dreamRs/shinyWidgets/issues/104#issuecomment-1060369899

**Comment by KimberlyEddleman** [comment]
Hi, I'm not sure why (because with inline=FALSE it should be choosing "block"), but if you change line 155 in module-selectizeGroup.Rmodule-selectizeGroup.R from
`   session = session, id = ns(paste0("container-", var)), display = ifelse(inline, "table-cell", "block")`
to
`   session = session, id = ns(paste0("container-", var)), display = ifelse(inline, "block", "block")`

the vertical alignment seems to work, at least it did when I downloaded the R directory, changed that line and put the it into my app. Not sure what other impacts that has, though as this is my first time using this module, but hopefully it helps others who need the vertical alignment to use this in their apps.

**Comment by pvictor** [comment]
You have to repeat argument `inline = FALSE` in the server module:

```r
res_mod <- callModule(
  module = selectizeGroupServer,
  id = "my-filters",
  data = mpg,
  vars = c("manufacturer", "model", "trans", "class"),
  inline = FALSE  # <<<---- here
)
```

**Comment by KimberlyEddleman** [comment]
Oh wow, yes that is much cleaner/easier, thank you! That seems to have worked in my code.
