### ISSUE TITLE
default date in airDatepicker one day earlier

### ISSUE THREAD

**Issue by dleopold** [dreamRs/shinyWidgets#505]
When I provide a date to the 'value' parameter the widget uses the day before as the default. Here is an example. When I run this, the widget defaults to 2022-07-13, though `value='2022-07-14'` is provided.

```
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  airDatepickerInput(
    inputId = "date",
    range=FALSE, 
    value="2022-07-14"
  ),
  verbatimTextOutput("res")
)

server <- function(input, output, session) {
  output$res <- renderPrint(input$date)
}

shinyApp(ui, server)

}
```

**Comment by pvictor** [comment]
What's your timezone ? I think it comes from the browser

**Comment by pvictor** [comment]
That's because dates are processed in the browser, try taping `new Date("2022-07-14")` in your JavaScript console see what happen. In `updateAirDateInput` there's a conversion done in R.

You can try installing development branch

```r
# install.packages("remotes")
remotes::install_github("dreamRs/shinyWidgets", ref = "airdatepicker3")
```
to see if it's better. It use latest [air-datepicker](https://github.com/t1m0n/air-datepicker) release and use [dayjs](https://github.com/iamkun/dayjs/) to manipulate dates in JS.

**Comment by dleopold** [comment]
You are right, typing new Date("2022-07-14") in the web browser console returns "2022-07-13". That is strange. In any case, I switched to the development branch you suggested and it seems to be working as expected now. Thank you.
