### ISSUE TITLE
Setting the width of the button in the dropdownButton

### ISSUE THREAD

**Issue by john-harrold** [dreamRs/shinyWidgets#508]
Hello,

I can use the width argument to set the width of the area when I click on the dropdown button. However I'd like to set the width of the button itself. Is there a way to do that?

Thanks

**Comment by pvictor** [comment]
Hello,

There's no builtin way to set button width. One method to setting a width to the button will be to add special CSS class to the button through the `status =` argument and then use CSS code to style the button (width, color, etc...). Here's an example: 

```r
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  
  tags$style(".btn-custom {width: 400px;}"), # custom CSS styles
  
  dropdownButton(
    inputId = "mydropdown",
    label = "Controls",
    icon = icon("sliders"),
    status = "primary btn-custom", # custom class for the button
    circle = FALSE,
    "Dropdown content"
  )
)

server <- function(input, output, session) {}

shinyApp(ui, server)
```

Otherwise you can look at `?dropMenu` which is similar but where the button is easier to customize .

Victor
