### ISSUE TITLE
DropdownButton seems to break the input$tabNames

### ISSUE THREAD

**Issue by madmark81** [dreamRs/shinyWidgets#60]
Hi Victor, 

I use input$tabnames to jump from one dashboardpage tab to previous or next according to the SO item found in the link at the bottom here. What I just found out is that putting any kind of dropdownbutton in the app will break this code for input$tabnames, because print(input$tabnames) now gives NULL instead of the page nr. 

Any clue why, and possibly a fix? 

https://stackoverflow.com/questions/44309328/generic-button-for-go-to-next-and-previous-tabitem-shiny

**Comment by pvictor** [comment]
Hi Mark,

This doesn't work with BigDataScientist's solution because of his Javascript function `getAllElementsWithAttribute`, as its name suggests, it retrieves all elements with the specified attribute, in this case it not only retrieves tabItems but also dropdowns (which share the attribute). If you want to use this solution, you'll have to rewrite this function to be more specific.

However, it works fine with Benjamin one.

**Comment by madmark81** [comment]
Ah yes that works now. Thanks!
